pool:
  vmImage: 'Ubuntu 16.04'

container: mabenoit/azuredevops-ansible-agent:latest

trigger:
  batch: true
  branches:
    include:
    - refs/heads/*
  paths:
    include:
    - example/
pr: none

variables:
  location: eastus
  # define 5 more variables: resourceGroupName, clientId, clientSecret, subscriptionId and tenantId in the build pipeline in UI

steps:
- script: |
    ansible --version
    cd $(system.defaultWorkingDirectory)/example
    ansible-playbook rg.yml --extra-vars "location=eastus resource_group_name=$(resourceGroupName)"
  displayName: 'Run Ansible Playbook'
  env:
      AZURE_TENANT: $(tenantId)
      AZURE_SUBSCRIPTION_ID: $(subscriptionId)
      AZURE_CLIENT_ID: $(clientId)
      AZURE_SECRET: $(clientSecret)
