pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  batch: true
  branches:
    include:
    - refs/heads/*
  paths:
    exclude:
    - example/
    - README.md

variables:
  imageName: 'azuredevops-ansible-agent'
  ansibleVersion: 2.7.9
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI

steps:
- bash: docker build -f $(system.defaultWorkingDirectory)/Dockerfile -t $(registryName)/$(imageName):$(ansibleVersion) -t $(registryName)/$(imageName):latest $(system.defaultWorkingDirectory)
  displayName: 'docker build'

- bash: docker login -u $(registryLogin) -p $(registryPassword)
  displayName: 'docker login'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

- bash: |
    docker push $(registryName)/$(imageName):$(ansibleVersion)
    docker push $(registryName)/$(imageName):latest
  displayName: 'docker push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
